### ISSUE TITLE
Chrome Version 114.0.5735.134 - Can't see items in Cloud Folder

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-drive#91] opened 2023-06-22 12:28 UTC
Seems I can see most all my folders relatively quickly, except my Phone Backup folder.   This one will just sit forever, and never render the items inside.

I'm attaching a small video showing this behavior.   (USA)

https://github.com/FilenCloudDienste/filen-drive/assets/105058921/26410152-1312-4c9e-9579-6a711056aebf

**Comment by Dwynr** [comment] 2023-06-23 11:13
Cannot reproduce. If you have a lot of files in a single folder, loading it will take pretty long due to all the metadata decryption happening.

(The video does not work)

Issue template example: https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by telrod11** [comment] 2023-06-23 21:08
Single folder but 360+ subfolders

**Comment by telrod11** [comment] 2023-06-25 15:56
https://github.com/FilenCloudDienste/filen-drive/assets/105058921/f048ebb5-a3d1-47ed-a4bd-e3b7ae743ca8

Try this one....

**Comment by Dwynr** [comment] 2023-06-25 16:45
Can you open the chrome dev tools (Shift + CTRL + J) and copy the complete log? There might be some errors in the console.

**Comment by telrod11** [comment] 2023-06-26 08:47
This?

Keypair updated
DOMException: Failed to read large IndexedDB value
2search.ts:52 DOMException: Failed to read large IndexedDB value
(anonymous) @ search.ts:52
2asyncToGenerator.js:6 Uncaught (in promise) DOMException: Failed to read large IndexedDB value
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://drive.filen.io/sm/50a6907fb78f9ce350ecd8437eec0dcc604ba21287893abed38c4313e34e04a6.map: Unexpected token '<', "<!doctype "... is not valid JSON
asyncToGenerator.js:6 Uncaught (in promise) DOMException: Failed to read large IndexedDB value
O @ asyncToGenerator.js:6
s @ asyncToGenerator.js:29
Promise.then (async)
O @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Drive.tsx:546
DOMException: Failed to read large IndexedDB value
Promise.catch (async)
(anonymous) @ Item.tsx:592
(anonymous) @ Item.tsx:631
rl @ react-dom.production.min.js:244
_c @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:283
xc @ react-dom.production.min.js:281
lc @ react-dom.production.min.js:273
ji @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267

**Comment by telrod11** [comment] 2023-06-26 08:58
I should add, Firefox will open that folder, albeit really slowly

**Comment by Dwynr** [comment] 2023-06-26 12:17
Found the issue, will be fixed in the next update. Thanks for reporting.

**Closed by Dwynr** 2023-06-26 12:17 UTC
